name: introducao_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.20.2
  my_simple_package: 
    # git:
    #   url: https://github.com/taynaramos/intro-dart
    path: ./packages/my_simple_package
      # ref: main

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
